### ISSUE TITLE
Update for WordPress 5.2?

### ISSUE THREAD

**Issue by danemco** [bagley/wptool#4]
Any plans to update this tool to the latest version of WordPress? Some functions no longer work, such as `wplogin`.

**Comment by bagley** [comment]
Sorry I didn't get back to you on this. There are no plans to make it work. I've been doing other things, and this one got pushed on the wayside. I'm actually archiving the project. I'd suggest Using WP-CLI and there's a plugin that will do the same as wplogin.

- [WP-CLI](https://wp-cli.org/) - Tool to manage WordPress.
- [WP-CLI Login Command](https://github.com/aaemnnosttv/wp-cli-login-command) - Plugin to login as a given user.
